"""
Experiment status tracker.

Scans data/outputs/ and figures/ to render the experiment matrix.

Principal experiment scope: 3 Dense sizes × 7 languages × 2 conditions = 42 inference cells.
The 26B-A4B (MoE) size is kept in SIZES so old runs still render; it is OUT OF SCOPE for the
principal experiment — see FUTURE_WORK.md.

Prints a markdown table to stdout AND writes STATUS.md so the project root
always has a single up-to-date snapshot.

Usage:
    python scripts/00_status.py
    python scripts/00_status.py --watch     # re-render every 30 s
"""

import argparse
import json
import time
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "data" / "outputs"
FIG_DIR = ROOT / "figures"
STATUS_PATH = ROOT / "STATUS.md"
CFG_PATH = ROOT / "configs" / "experiment.yaml"

SIZES = ["e2b", "e4b", "26b", "31b"]
CONDITIONS = ["base", "abliterated"]
COND_LABEL = {"base": "base", "abliterated": "abl"}

PENDING = "·"
INFERRED = "◐"   # inference done, judging pending
JUDGED = "✓"     # judged
LEGEND = (f"`{PENDING}` pending  ·  `{INFERRED}` inferred (judging pending)  "
          f"·  `{JUDGED}` judged (compliance %)")


def load_languages():
    if not CFG_PATH.exists():
        return ["en", "es", "zh", "pt", "de", "ar", "hi"]
    with open(CFG_PATH) as f:
        return yaml.safe_load(f)["languages"]


def cell_state(size, condition, lang):
    raw = OUT_DIR / f"{size}_{condition}_{lang}.jsonl"
    judged = OUT_DIR / f"{size}_{condition}_{lang}_judged.jsonl"
    if judged.exists():
        with open(judged) as f:
            data = [json.loads(line) for line in f]
        if not data:
            return INFERRED, None
        rate = sum(r.get("complied", False) for r in data) / len(data)
        return JUDGED, rate
    if raw.exists():
        return INFERRED, None
    return PENDING, None


def cell_str(state, rate):
    if state == JUDGED and rate is not None:
        return f"{JUDGED} {rate * 100:.0f}%"
    return state


def mechanistic_state(size):
    refusal = OUT_DIR / f"refusal_directions_{size}.pt"
    silhouette = OUT_DIR / "silhouette_scores.csv"
    has_refusal = refusal.exists()
    has_silhouette = False
    if silhouette.exists():
        try:
            with open(silhouette) as f:
                has_silhouette = any(line.startswith(size + ",") or
                                     ("," + size + ",") in line
                                     for line in f)
        except OSError:
            pass
    return has_refusal, has_silhouette


def build_matrix(languages):
    rows = []
    for size in SIZES:
        for cond in CONDITIONS:
            row = {"size": size, "condition": cond, "label": f"{size.upper()} {COND_LABEL[cond]}"}
            for lang in languages:
                state, rate = cell_state(size, cond, lang)
                row[lang] = cell_str(state, rate)
                row[lang + "_state"] = state
            rows.append(row)
    return rows


def format_md(rows, languages):
    lines = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append("# Experiment Matrix Status")
    lines.append("")
    lines.append(f"_Auto-generated by `scripts/00_status.py` — {now}_")
    lines.append("")
    lines.append("## Inference × Judging")
    lines.append("")
    lines.append(LEGEND)
    lines.append("")
    header = "| Cell | " + " | ".join(l.upper() for l in languages) + " |"
    sep = "|------|" + "|".join(["------"] * len(languages)) + "|"
    lines.append(header)
    lines.append(sep)
    for r in rows:
        cells = [r[l] for l in languages]
        lines.append(f"| **{r['label']}** | " + " | ".join(cells) + " |")
    lines.append("")

    # Per-size summary: count and totals (denominator = languages × conditions)
    total_per_size = len(languages) * len(CONDITIONS)
    lines.append("## Per-size progress")
    lines.append("")
    lines.append(f"| Size | Inferences (of {total_per_size}) | Judged (of {total_per_size}) | Refusal dirs | Silhouette |")
    lines.append("|------|--------------------|----------------|--------------|-----------|")
    for size in SIZES:
        n_inferred = 0
        n_judged = 0
        for cond in CONDITIONS:
            for lang in languages:
                state, _ = cell_state(size, cond, lang)
                if state in (INFERRED, JUDGED):
                    n_inferred += 1
                if state == JUDGED:
                    n_judged += 1
        has_refusal, has_silhouette = mechanistic_state(size)
        lines.append(
            f"| {size.upper()} | {n_inferred}/{total_per_size} | {n_judged}/{total_per_size} | "
            f"{'✓' if has_refusal else '·'} | {'✓' if has_silhouette else '·'} |"
        )
    lines.append("")

    # Aggregate artifacts
    lines.append("## Aggregate artifacts")
    lines.append("")
    items = [
        ("compliance_rates.csv", OUT_DIR / "compliance_rates.csv"),
        ("silhouette_scores.csv", OUT_DIR / "silhouette_scores.csv"),
        ("judge_unparseable.log", OUT_DIR / "judge_unparseable.log"),
        ("figures/silhouette_heatmap.png", FIG_DIR / "silhouette_heatmap.png"),
        ("figures/compliance_abliterated_heatmap.png",
         FIG_DIR / "compliance_abliterated_heatmap.png"),
        ("figures/size_vs_compliance.png", FIG_DIR / "size_vs_compliance.png"),
    ]
    for name, path in items:
        mark = "✓" if path.exists() else "·"
        lines.append(f"- {mark} `{name}`")
    lines.append("")

    return "\n".join(lines)


def render():
    languages = load_languages()
    rows = build_matrix(languages)
    md = format_md(rows, languages)
    STATUS_PATH.write_text(md, encoding="utf-8")
    print(md)
    print(f"\nSaved → {STATUS_PATH.relative_to(ROOT)}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--watch", action="store_true",
                        help="Re-render every 30 s (Ctrl-C to stop)")
    args = parser.parse_args()

    if not args.watch:
        render()
        return

    try:
        while True:
            print("\033[2J\033[H", end="")  # clear terminal
            render()
            time.sleep(30)
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
